# Generated by Django 6.0.1 on 2026-01-15 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_audit_entity_8edb54_idx'), models.Index(fields=['performed_at'], name='audit_audit_perform_cca95c_idx')],
            },
        ),
    ]
